In [ ]:
# business 음식점 필터링 & 필요 컬럼 추출 

# 0. 라이브러리 불러오기
import pandas as pd
import os

# 1. 데이터 경로 설정
# BUSINESS_JSON_PATH = '../data/raw/business.json'
BUSINESS_JSON_PATH = '../data/yelp_academic_dataset_business.json'

# 2. 데이터 불러오기
def load_business_data(path):
    """business.json 불러오기"""
    print(f"Loading business data from {path}")
    return pd.read_json(path, lines=True)

# 3. 음식점 데이터만 필터링
def filter_restaurants(df):
    """카테고리 중 'Restaurants' 포함된 데이터만 추출"""
    restaurant_df = df[df['categories'].str.contains('Restaurants', na=False)].copy()
    print(f"Filtered {len(restaurant_df)} restaurant entries")
    return restaurant_df

# 4. 필요한 컬럼만 추출
def simplify_restaurant_data(df):
    """business_id, name, city, state, stars, review_count만 추출"""
    simple_df = df[[
        'business_id', 'name', 'city', 'state', 'stars', 'review_count'
    ]].copy()
    print(f"Simplified data shape: {simple_df.shape}")
    return simple_df

# 5. 실행 (불러오기 + 필터링 + 간소화)
business_df = load_business_data(BUSINESS_JSON_PATH)
restaurant_df = filter_restaurants(business_df)
restaurant_simple_df = simplify_restaurant_data(restaurant_df)

# 6. 데이터 확인
restaurant_simple_df.head()

Loading business data from ../data/yelp_academic_dataset_business.json
Filtered 52268 restaurant entries
Simplified data shape: (52268, 6)

,business_id,name,city,state,stars,review_count
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,4.0,80
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,Ashland City,TN,2.0,6
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,Affton,MO,3.0,19
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,Nashville,TN,1.5,10
11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,Tampa Bay,FL,4.0,10

In [ ]:
# 0. 라이브러리 불러오기
import pandas as pd
import os

# 1. 데이터 경로 설정
BUSINESS_JSON_PATH = '../data/yelp_academic_dataset_business.json'

# 2. 데이터 불러오기
def load_business_data(path):
    """business.json 불러오기"""
    print(f"Loading business data from {path}")
    return pd.read_json(path, lines=True)

# 3. 음식점 데이터만 필터링
def filter_restaurants(df):
    """카테고리 중 'Restaurants' 포함된 데이터만 추출"""
    restaurant_df = df[df['categories'].str.contains('Restaurants', na=False)].copy()
    print(f"Filtered {len(restaurant_df)} restaurant entries")
    return restaurant_df

# 4. 필요한 컬럼만 추출
def simplify_restaurant_data(df):
    """business_id, name, city, state, stars, review_count만 추출"""
    simple_df = df[[
        'business_id', 'name', 'city', 'state', 'stars', 'review_count'
    ]].copy()
    print(f"Simplified data shape: {simple_df.shape}")
    return simple_df

# 5. 실행 (불러오기 + 필터링 + 간소화)
business_df = load_business_data(BUSINESS_JSON_PATH)
restaurant_df = filter_restaurants(business_df)
restaurant_simple_df = simplify_restaurant_data(restaurant_df)

# 6. 유니크한 도시 목록 확인 (소문자로 정리해서 중복 제거)
cities = restaurant_simple_df['city'].dropna().str.lower().unique()
print(f"Unique city count: {len(cities)}")   

# 7. 도시 목록 일부 미리 보기 (앞에서 20개만 보기)
print("Sample cities:", sorted(cities)[:20])

# 8. 싱가포르 있는지 확인
if 'singapore' in cities:
    print("✅ 'singapore' is in the dataset.")
else:
    print("❌ 'singapore' not found in the dataset.")

Loading business data from ../data/yelp_academic_dataset_business.json
Filtered 52268 restaurant entries
Simplified data shape: (52268, 6)
Unique city count: 859
Sample cities: ['abington', 'abington township', 'affton', 'aldan', 'algiers', 'alloway', 'alton', 'ambler', 'antioch', 'apollo beach', 'arabi', 'ardmore', 'arnold', 'ashland', 'ashland city', 'aston', 'atco', 'audubon', 'audubon ', 'avon']
❌ 'singapore' not found in the dataset.

In [ ]:
# review 데이터 필터링링

# 0. 라이브러리 불러오기
import pandas as pd

# 1. 경로 설정
REVIEW_JSON_PATH = '../data/yelp_academic_dataset_review.json'

# 2. 데이터 불러오기 (용량이 크기 때문에 일부만 불러오거나 chunk로 나눠서도 가능)
def load_review_data(path):
    """리뷰 데이터 불러오기"""
    print(f"Loading review data from {path}")
    return pd.read_json(path, lines=True)

# 3. 음식점 리뷰만 필터링
def filter_reviews_by_restaurants(review_df, restaurant_df):
    """restaurant_df의 business_id에 해당하는 리뷰만 필터링"""
    restaurant_ids = set(restaurant_df['business_id'])
    filtered_reviews = review_df[review_df['business_id'].isin(restaurant_ids)].copy()
    print(f"Filtered {len(filtered_reviews)} restaurant-related reviews")
    return filtered_reviews

# 4. 실행
review_df = load_review_data(REVIEW_JSON_PATH)
restaurant_reviews = filter_reviews_by_restaurants(review_df, restaurant_simple_df)

# 5. 데이터 확인
restaurant_reviews.head()

Loading review data from ../data/yelp_academic_dataset_review.json
Filtered 4724471 restaurant-related reviews

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,1,2,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31

In [7]:
# data load 최종버전

# 0. 라이브러리 불러오기
import pandas as pd
import os

# 1. 데이터 경로 설정
BUSINESS_JSON_PATH = '../data/yelp_academic_dataset_business.json'
REVIEW_JSON_PATH = '../data/yelp_academic_dataset_review.json'

# 2. 비즈니스 데이터 불러오기
def load_business_data(path):
    """business.json 불러오기"""
    print(f"Loading business data from {path}")
    return pd.read_json(path, lines=True)

# 3. 음식점만 필터링
def filter_restaurants(df):
    """카테고리 중 'Restaurants' 포함된 데이터만 추출"""
    restaurant_df = df[df['categories'].str.contains('Restaurants', na=False)].copy()
    print(f"Filtered {len(restaurant_df)} restaurant entries")
    return restaurant_df

# 4. 필요한 컬럼만 추출
def simplify_restaurant_data(df):
    """business_id, name, city, state, stars, review_count만 추출"""
    simple_df = df[[ 'business_id', 'name', 'city', 'state', 'stars', 'review_count' ]].copy()
    print(f"Simplified data shape: {simple_df.shape}")
    return simple_df

# 5. 리뷰 데이터 불러오기
def load_review_data(path):
    """review.json 불러오기"""
    print(f"Loading review data from {path}")
    return pd.read_json(path, lines=True)

# 6. 음식점 리뷰만 필터링
def filter_restaurant_reviews(review_df, restaurant_df):
    """business_id 기준으로 음식점 리뷰만 추출"""
    restaurant_ids = set(restaurant_df['business_id'])
    filtered_reviews = review_df[review_df['business_id'].isin(restaurant_ids)].copy()
    print(f"Filtered {len(filtered_reviews)} restaurant-related reviews")
    return filtered_reviews

# 7. 실행
business_df = load_business_data(BUSINESS_JSON_PATH)
restaurant_df = filter_restaurants(business_df)
restaurant_simple_df = simplify_restaurant_data(restaurant_df)

review_df = load_review_data(REVIEW_JSON_PATH)
restaurant_reviews = filter_restaurant_reviews(review_df, restaurant_simple_df)

# 8. 저장
restaurant_simple_df.to_csv('../data/restaurant_business.csv', index=False)
restaurant_reviews.to_csv('../data/restaurant_reviews.csv', index=False)

# 9. 샘플 확인
print(restaurant_simple_df.head())
print(restaurant_reviews.head())

Loading business data from ../data/yelp_academic_dataset_business.json
Filtered 52268 restaurant entries
Simplified data shape: (52268, 6)
Loading review data from ../data/yelp_academic_dataset_review.json
Filtered 4724471 restaurant-related reviews
               business_id                   name          city state  stars  \
3   MTSW4McQd7CbVtyjqoe9mw     St Honore Pastries  Philadelphia    PA    4.0
5   CF33F8-E6oudUQ46HnavjQ         Sonic Drive-In  Ashland City    TN    2.0
8   k0hlBqXX-Bt0vf1op7Jr1w  Tsevi's Pub And Grill        Affton    MO    3.0
9   bBDDEgkFA1Otx9Lfe7BZUQ         Sonic Drive-In     Nashville    TN    1.5
11  eEOYSgkmpB90uNA7lDOMRA  Vietnamese Food Truck     Tampa Bay    FL    4.0

    review_count
3             80
5              6
8             19
9             10
11            10
                review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw
2  saUsX_uimxRlCVr67Z4Jig  8g_iMtfSiwikVnbP2etR0A  YjUWPpI6HXG530lwP-fb2A
3  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA
4  Sx8TMOWLNuJBWer-0pcmoA  bcjbaE6dDog4jkNY91ncLQ  e4Vwtrqf-wpJfwesgvdgxQ
5  JrIxlS1TzJ-iCu79ul40cQ  eUta8W_HdHMXPzLBBZhL1A  04UD14gamNjLY0IDYVhHJg

   stars  useful  funny  cool  \
0      3       0      0     0
2      3       0      0     0
3      5       1      0     1
4      4       1      0     1
5      1       1      2     1

                                                text                date
0  If you decide to eat here, just be aware it is... 2018-07-07 22:09:11
2  Family diner. Had the buffet. Eclectic assortm... 2014-02-05 20:30:30
3  Wow!  Yummy, different,  delicious.   Our favo... 2015-01-04 00:01:03
4  Cute interior and owner (?) gave us tour of up... 2017-01-14 20:54:15
5  I am a long term frequent customer of this est... 2015-09-23 23:10:31